# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      TAGS: |
        docker.io/ABCddd/foobar:1.2.3
        docker.io/ABCddd/foobar:1.2.3-plusSomething

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Before
        run: echo Tags='${{ env.TAGS }}'

      - name: Normalize TAGS
        shell: bash
        id: normalize_tags
        run: echo "::set-output name=tags::$(echo '${{ env.TAGS }}' | tr '[:upper:]' '[:lower:]')"

      # Runs a set of commands using the runners shell
      - name: After
        run: echo Tags='${{ steps.normalize_tags.outputs.tags }}'
